version: "3.8"
services:
  backend:
    container_name: "trust_studio_backend"
    build:
      context: trustminer-backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
      - frontend
  db:
    container_name: "trust_studio_db"
    image: mongo
  frontend:
    container_name: "trust_studio_frontend"
    build:
      context: trustminer-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    network_mode: "host"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
