version: "3.8"
services:
  backend:
    container_name: "trust_studio_backend"
    build:
      context: trustminer-backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ssl:/etc/ssl
    links:
      - db
      - frontend
  db:
    container_name: "trust_studio_db"
    image: mongo
  frontend:
    container_name: "trust_studio_frontend"
    build:
      context: trustminer-frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ssl:/etc/ssl
    ports:
      - "3000:443"
    network_mode: "host"
volumes:
  ssl: